version: 0.0
os: linux
files:
  - source: /root 
    destination: /root/lottery
hooks:
  ApplicationStop:
    - echo app stop
  ApplicationStart:
    - location: /root/start.sh
      timeout: 300
      runas: ec2-user