version: 0.0
os: linux
files:
  - source: /
    destination: /root/lottery
permissions:
  - object: /root/lottery/
    owner: root
    group: root
    mode: 755
hooks:
  AfterInstall:
    - location: install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: root