version: 0.2

env:
  variables:
    TEST_ENV_VARIABLE: myArtifactName
    
phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - npm install
      - npm run build
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'