version: 0.1

phases:
  install:
    runtime-version:
      nodejs: 10
    commands:
      -npm install
  build:
    commands:
      - echo Build completed on `date`
      - npm package
      - npm install
artifacts:
  files:
    - '**/*'